apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: airflow-dags
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/airflow-dags
